/* Automatically generated by './build/bin/build-entry.js' */

import Throttle from '../packages/throttle.js';
import MySetInterval from '../packages/setInterval.js';
import HandleLimitTask from '../packages/promiseLimit.js';
import Debounce from '../packages/Debounce.js';

export default {
  version: '1.0.0',
  Throttle,
  MySetInterval,
  HandleLimitTask,
  Debounce
};
